# Generated by Django 3.2.7 on 2021-12-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20211204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_item',
            name='class_number',
            field=models.CharField(default='temp', max_length=300),
        ),
        migrations.AddField(
            model_name='class_item',
            name='mnemonic',
            field=models.CharField(default='temp', max_length=300),
        ),
        migrations.AddField(
            model_name='class_item',
            name='prof',
            field=models.CharField(default='temp', max_length=300),
        ),
    ]
