# Generated by Django 3.2.7 on 2021-12-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20211204_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_item',
            name='class_number',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='class_item',
            name='mnemonic',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='class_item',
            name='prof',
            field=models.CharField(max_length=300),
        ),
    ]
