# Generated by Django 3.2.7 on 2021-12-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20211205_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_item',
            name='semester',
            field=models.CharField(default='temp', max_length=300),
        ),
    ]
