# Generated by Django 3.2.7 on 2021-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_class_item_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_item',
            name='semester',
            field=models.CharField(max_length=300),
        ),
    ]
